### ISSUE TITLE
Really slow tabbing.

### ISSUE THREAD

**Issue by fourq** [brentlintner/vim-settings#25]
Anyone else notice incredibly show tabbing in insert mode? I've made several changes in my girl so I'm not sure yet if it's just mine.

**Comment by brentlintner** [comment]
@fourq not sure if I see the same. Seems to be pretty responsive. Any specific file types?

**Comment by fourq** [comment]
javascript is what I'm noticing it on. I'm not sure what's going on yet.

**Comment by brentlintner** [comment]
Just double checked some JS files.. Hmm. Seems to be good for me? Closing this for now!
